### ISSUE TITLE
digital ocean account

### ISSUE THREAD

**Issue by scottstensland** [theincorruptibles/project_management#5]
during the IT handover from Morgan when I logged into Digital Ocean I could see the servers 

now they are gone ... looks like Morgan moved the machines ?  dunno 

Who is paying for the servers ?  these are two boxes :   one dev (512 mb RAM)  the other prod 1gb

since this github repo is not private I will not mention the IP addresses here

I can login onto them both however cannot reach the digital ocean account which is the DNS admin side of running admin for those boxes

**Comment by jazztpt** [comment]
I also have a login to digital ocean but don't see any droplets.  Let's ping @mrgnr .  By the way, I'm not in the habit of checking github (your set of tasks is the only reason I currently have to be on here).  Could you also ping me in rocket chat if you have a question?  Thank you!

**Comment by jazztpt** [comment]
Morgan moved these over to the team account.  Thank you @mrgnr !
